<html lang="en">
    <head>
        <title>ZiiPHP Frameword</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <meta name="desc" content="test">
        <link rel="apple-touch-icon" sizes="180x180" href="<?= UrlHelper::asset('/apple-touch-icon.png') ?>">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= UrlHelper::asset('/favicon-32x32.png') ?>">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= UrlHelper::asset('/favicon-16x16.png') ?>">
    </head>
    <body>
        <?= $yield_content ?>
    </body>
</html>